safe:        true
url:         https://joway.github.io/Utopia

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
markdown:    rdiscount

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids:    true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

permalink:    /:title

title:        泛彼柏舟
alt:          Joway's blog
author:
  name:       Joway
copyright:
  - Another Tech Blog  <a href="https://joway.wang" target="_blank">  joway.wang  </a>

paginate:     5
