# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
gems:
                  - jekyll-sitemap

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            neaix
description:      '慢慢走'
baseurl:          /
url:              http://neaix.com
domain:           neaix.com
email:            neaix@hotmail.com
twitter_username: ztpala
github_username:  pala
timezone:         America/New_York
subscribe:        
exclude:          [ README.md, newpost.rb, CNAME ]

author:
  url:            neaix.com

paginate:         5

github:
  repo:           https://github.com/pala/neaix.github.io

disqus_shortname: neaix
