# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
highlighter: pygments

# Site settings
title: "Rajath Kumar"
description: > # this means to ignore newlines until "email:"
   Things that I have done, learnt and thought about.

email: neaix@hotmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/wave1.png"

name: 'Bin lau'
author: 'Bin lau'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://neaix.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/rajathkmp
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="
  - icon: github
    url:  https://github.com/neaix
    desc: Fork me on github
    title: GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	
#    url:	
#    desc: Connect with me facebook
#    title: Facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="



#  - icon:	google-plus
#    url:	https://google.com/+rajathkumar
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
