#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
  local: "http://localhost:4000"
  live: "http://hop.ie"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 768
  - 1024
  
#Type page URL paths below, here are a couple of examples
paths:
  home: /
  about: /about/
  blogpost: /blog/holy-grail/

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10
